[build]
  command = "pnpm run build"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    
    